### PR TITLE
Added Materio Free Vuetify VueJS Laravel Admin Template

### PR DESCRIPTION
**Pull request by saanvi-ts**
### Materio Free Vuetify VueJS  Laravel Admin Template

Materio Free  Vuetify VueJS Laravel Admin Dashboard Template – is the most developer-friendly & highly customizable Admin Dashboard Template based on Laravel.

**Features:**

- Pure Vue js, Laravel
- Utilizes Vuex, Vue Router, Webpack
- 1 Dashboard
- Material Icons
- Basic cards
- Fully Responsive Layout
- Organized Folder Structure
- Clean & Commented Code

Check the demo here: https://themeselection.com/demo/materio-vuetify-vuejs-laravel-admin-template-free/demo/dashboard

### CODE REVIEW

**Comment by rmjordas** [comment]
Thanks @saanvi-ts 🎉

**Comment by saanvi-ts** [comment]
Thank you for including it in the list.👍🏻

**Comment by saanvi-ts** [comment]
I was wondering if the template will be included here (https://awesome-vue.js.org/projects-using-vue-js/open-source.html) as well?

**Comment by rmjordas** [comment]
The page you linked was updated almost immediately after the changes were merged and there should be a prompt that tells you that there are updates available for the page. But you can also hard refresh the page by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>.

image

**Comment by saanvi-ts** [comment]
Ok. Thanks.🙂

**Pull request merged**
